# Generated by Django 2.0.5 on 2018-05-22 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20180522_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
