# Generated by Django 2.0.5 on 2018-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_auto_20180522_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='dateAdded',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
